before_install:
 - sudo add-apt-repository ppa:trevorbernard/zeromq -y
 - sudo apt-get update -y
 - sudo apt-get install libzmq3-dev libpgm-dev jzmq
language: clojure
lein: lein2
script: lein2 all test
jdk:
  - openjdk7
  - openjdk6
